name: aimlc

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  aimlc:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /aimlc') ||
      startsWith(github.event.comment.body, '/aimlc')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run aimlc
        uses: harimuliawan999-sys/ai-muliawan-long-code/github@latest
        env:
          aimlc_API_KEY: ${{ secrets.aimlc_API_KEY }}
          aimlc_PERMISSION: '{"bash": "deny"}'
        with:
          model: aimlc/claude-opus-4-5
